-- Your SQL goes here
CREATE TABLE items (
  id INTEGER PRIMARY KEY NOT NULL,
  name VARCHAR NOT NULL,
  location_id INTEGER NOT NULL,
  team_id INTEGER,
  amount INTEGER DEFAULT 0,
  barcode VARCHAR(15),
  for_rent BOOLEAN NOT NULL DEFAULT 'f'
);

CREATE TABLE locations (
  id INTEGER PRIMARY KEY NOT NULL,
  name VARCHAR(50) NOT NULL,
  warehouse_id INTEGER NOT NULL
);

CREATE TABLE teams (
  id INTEGER PRIMARY KEY NOT NULL,
  name VARCHAR(50) NOT NULL,
  teamlead_id INTEGER
);

CREATE TABLE users (
  id INTEGER PRIMARY KEY NOT NULL,
  name VARCHAR(50) NOT NULL,
  team_id INTEGER
);

CREATE TABLE warehouses (
  id INTEGER PRIMARY KEY NOT NULL,
  name VARCHAR(50) NOT NULL,
  address VARCHAR,
  capacity VARCHAR(50)
);

