[package]
name = "inventorer"
version = "0.1.0"
authors = ["Francis Begyn <francis.begyn@gmail.com>"]
edition = "2018"

[dependencies]
diesel = { version = "1.0.0", features = ["sqlite"] }
dotenv = "0.9.0"
